/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirectoriio;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Estudiantes
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ControladorDirectoriio controladorDirectoriio;
    
    String ruta;
    
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        controladorDirectoriio = new ControladorDirectoriio(ruta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnListarDirectorios = new javax.swing.JButton();
        btnListarArchivosOcultos = new javax.swing.JButton();
        btnListarDirectoriosOcultos = new javax.swing.JButton();
        btnListarArchivos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDirectorios = new javax.swing.JList<>();
        btnMostrarInformacion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaInformacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gestionarMenu = new javax.swing.JMenu();
        crearMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Directorios");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Directorios :)");

        jLabel2.setText("Ingrese la ruta:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnListarDirectorios.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnListarDirectorios.setText("Listar Directorios");
        btnListarDirectorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDirectoriosActionPerformed(evt);
            }
        });

        btnListarArchivosOcultos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnListarArchivosOcultos.setText("Listar Archivos Ocultos ");
        btnListarArchivosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarArchivosOcultosActionPerformed(evt);
            }
        });

        btnListarDirectoriosOcultos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnListarDirectoriosOcultos.setText("Listar Directorios Ocultos");
        btnListarDirectoriosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDirectoriosOcultosActionPerformed(evt);
            }
        });

        btnListarArchivos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnListarArchivos.setText("Listar Archivos");
        btnListarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarArchivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListarDirectorios)
                .addGap(18, 18, 18)
                .addComponent(btnListarArchivos)
                .addGap(18, 18, 18)
                .addComponent(btnListarArchivosOcultos)
                .addGap(18, 18, 18)
                .addComponent(btnListarDirectoriosOcultos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarDirectorios)
                    .addComponent(btnListarArchivosOcultos)
                    .addComponent(btnListarDirectoriosOcultos)
                    .addComponent(btnListarArchivos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lstDirectorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDirectoriosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDirectorios);

        btnMostrarInformacion.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMostrarInformacion.setText("Mostrar Informacion");
        btnMostrarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInformacionActionPerformed(evt);
            }
        });

        txtAreaInformacion.setColumns(20);
        txtAreaInformacion.setRows(5);
        jScrollPane2.setViewportView(txtAreaInformacion);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Informacion:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnMostrarInformacion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnMostrarInformacion)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        gestionarMenu.setText("Gestionar Directorio");

        crearMenuItem.setText("Crear");
        crearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMenuItemActionPerformed(evt);
            }
        });
        gestionarMenu.add(crearMenuItem);

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        gestionarMenu.add(jMenuItem1);

        jMenuItem2.setText("Renombrar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        gestionarMenu.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        gestionarMenu.add(jMenuItem3);

        jMenuBar1.add(gestionarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnListarDirectoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDirectoriosActionPerformed
        ruta = txtRuta.getText();
        
        if(ruta.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese una ruta");
        }else{
            List<String> lista = controladorDirectoriio.listarDirectorios(ruta);
            
            if(lista!=null){
                limpiarLista();
                ingresarDatosLista(lista);
            }else{
                limpiarLista();
                JOptionPane.showMessageDialog(this, "La ruta no contiene directorios o ruta incorrecta");
            }
        }
    }//GEN-LAST:event_btnListarDirectoriosActionPerformed

    private void btnListarArchivosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarArchivosOcultosActionPerformed
        ruta = txtRuta.getText();
        
        if(ruta.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese una ruta");
        }else{
            List<String> lista = controladorDirectoriio.listarArchivosOcultos(ruta);
            
            if(lista!=null){
                limpiarLista();
                ingresarDatosLista(lista);
            }else{
                limpiarLista();
                JOptionPane.showMessageDialog(this, "La ruta no contiene archivos ocultos o ruta incorrecta");
            }
        }
    }//GEN-LAST:event_btnListarArchivosOcultosActionPerformed

    private void btnListarDirectoriosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDirectoriosOcultosActionPerformed
        ruta = txtRuta.getText();
        
        if(ruta.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese una ruta");
        }else{
            
            List<String> lista = controladorDirectoriio.listarDirectoriosOcultos(ruta);
            if(lista != null){
                limpiarLista();
                ingresarDatosLista(lista);
            }else{
                JOptionPane.showMessageDialog(this, "La ruta no coentiene Directorios ocultos o ruta incorrecta");
            }
        }
    }//GEN-LAST:event_btnListarDirectoriosOcultosActionPerformed

    private void btnListarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarArchivosActionPerformed
        ruta = txtRuta.getText();
        
        if(ruta.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese una ruta");
        }else{
            
            List<String> lista = controladorDirectoriio.listarArchivos(ruta);
            if(lista != null){
                limpiarLista();
                ingresarDatosLista(lista);
            }else{
                JOptionPane.showMessageDialog(this, "La ruta no coentiene Archivos o ruta incorrecta");
            }
        }
    }//GEN-LAST:event_btnListarArchivosActionPerformed

    private void crearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMenuItemActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del nuevo directorio: ");
        ruta = txtRuta.getText();
        controladorDirectoriio.crearDirectorio(ruta, nombre);
        actualizarListaCrear(nombre);
    }//GEN-LAST:event_crearMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(!lstDirectorios.isSelectionEmpty()){
            int opcion = JOptionPane.showConfirmDialog(this, "Desea eliminar este directorio", "Eliminar Directorio", JOptionPane.YES_NO_OPTION);
            if(opcion==JOptionPane.YES_OPTION){
                String nombre = lstDirectorios.getSelectedValue();
                ruta = txtRuta.getText();
                controladorDirectoriio.eliminarDirectorio(ruta, nombre);
                int pos = lstDirectorios.getSelectedIndex();
                actualizarModeloEliminar(pos);
            }else{
                JOptionPane.showMessageDialog(this, "Elemento no eliminado");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Primero señale un elemento de la lista");
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(!lstDirectorios.isSelectionEmpty()){
            String nuevo = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre del Directorio: ");
            ruta = txtRuta.getText();
            String nombre = lstDirectorios.getSelectedValue();
            controladorDirectoriio.renombrarDirectorio(ruta, nombre, nuevo);
            int pos = lstDirectorios.getSelectedIndex();
            actualizarListaActualizar(nuevo, pos);
        }else{
            JOptionPane.showMessageDialog(this, "Primero señale un elemento de la lista");
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnMostrarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInformacionActionPerformed
        if(!lstDirectorios.isSelectionEmpty()){
            String nombre = lstDirectorios.getSelectedValue();
            ruta = txtRuta.getText();
            
            String texto = controladorDirectoriio.mostrarInformacion(ruta, nombre);
            
            txtAreaInformacion.setText(texto);
        }
    }//GEN-LAST:event_btnMostrarInformacionActionPerformed

    private void lstDirectoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDirectoriosMouseClicked
        if(!lstDirectorios.isSelectionEmpty()){
            txtAreaInformacion.setText("");
        }
    }//GEN-LAST:event_lstDirectoriosMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void actualizarListaCrear(String name){
        DefaultListModel modelo = (DefaultListModel) lstDirectorios.getModel();
        modelo.addElement(name);
        lstDirectorios.setModel(modelo);
        lstDirectorios.clearSelection();
    }
    
    public void actualizarListaActualizar(String name, int pos){
        DefaultListModel modelo = (DefaultListModel) lstDirectorios.getModel();
        modelo.addElement(name);
        modelo.remove(pos);
        lstDirectorios.setModel(modelo);
        lstDirectorios.clearSelection();
    }
    
    public void actualizarModeloEliminar(int pos){
        DefaultListModel modelo = (DefaultListModel) lstDirectorios.getModel();
        modelo.remove(pos);
        lstDirectorios.setModel(modelo);
        lstDirectorios.clearSelection();
    }
    public void ingresarDatosLista(List<String> lista){
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();

        for (String nombre : lista) {
            modelo.addElement(nombre);
        }
        lstDirectorios.setModel(modelo);
    }
    
    public void limpiarLista() {
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();
        lstDirectorios.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarArchivos;
    private javax.swing.JButton btnListarArchivosOcultos;
    private javax.swing.JButton btnListarDirectorios;
    private javax.swing.JButton btnListarDirectoriosOcultos;
    private javax.swing.JButton btnMostrarInformacion;
    private javax.swing.JMenuItem crearMenuItem;
    private javax.swing.JMenu gestionarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstDirectorios;
    private javax.swing.JTextArea txtAreaInformacion;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
